# Configuration for PubMed Screener Script

# --- Core Settings ---
email = "jorrit332@gmail.com"
research_question = "Are there molecules interacting with TSHR that are not its natural ligands but do affect cAMP production?"
ollama_url = "http://localhost:11434/api/generate"
ollama_model = "gemma3"
ollama_request_timeout = 180
ollama_num_ctx = 32768
thinking = false
request_delay_seconds = 1
output_dir = "tiab_screening"
articles_file = "articles.json"
# --- Criteria Files ---
inclusion_criteria_file = "inclusion_criteria.txt"
exclusion_criteria_file = "exclusion_criteria.txt"

# --- TIAB Screening Settings ---
tiab_prompt_file = "prompts/tiab_prompt.txt" 
pmid_input_file = "pmid_for_review.txt"
pmid_batch_size = 25

# --- PDF Fetching Settings ---
fetch_pdfs = true
pdf_download_dir = "pdfs"
unpaywall_email = "jorrit332@gmail.com"

# --- Full-Text Screening (FTS) Settings ---
fts_enabled = true
fts_prompt_file = "prompts/fts_prompt.txt"
fts_output_dir = "fts_screening"

# --- Molecule Extraction Settings ---
mol_extraction_enabled = true
mol_extraction_prompt_file = "prompts/mol_extract_prompt.txt"
mol_extraction_output_file = "results.txt"